### ISSUE TITLE
libstxxl fails to build using clang on OS X pre-10.9

### ISSUE THREAD

**Issue by mistydemeo** [stxxl/stxxl#7]
When building using clang on Mac OS X before 10.9, libstxxl tries to include C++11 headers when building in non-C++11 mode.

Sample build output:

```
In file included from /tmp/libstxxl-hmGD/stxxl-1.4.0/lib/common/verbose.cpp:18:
In file included from /tmp/libstxxl-hmGD/stxxl-1.4.0/include/stxxl/bits/common/timer.h:22:
In file included from /tmp/libstxxl-hmGD/stxxl-1.4.0/include/stxxl/bits/common/utils.h:30:
/tmp/libstxxl-hmGD/stxxl-1.4.0/include/stxxl/bits/compat/type_traits.h:20:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
```

A full log can be found here: https://gist.github.com/mistydemeo/0572287719e6a4cb9153

This was built using Homebrew, from the 1.4.0 tarball with commit d23dd29b9492061a8da2201ab2585914b66bb9c3 applied as a patch.

It looks like it's using the first part of the conditional, guarded by `#if __cplusplus >= 201103L`, and not the next part: https://github.com/stxxl/stxxl/blob/master/include/stxxl/bits/compat/type_traits.h#L32-L35
